AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ETL Backend
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: ./src/index.zip
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
        - SNSCrudPolicy:
            TopicName: !GetAtt SNS.TopicName
      Layers:
        - "arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-pandas:18"
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          SNS_TOPIC_ARN:
            Ref: SNS
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 9 * * ? *)'
            Name: ETLSchedule
            Description: ETL Covid Data
            Enabled: True

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Date
        Type: String
      TableName:

  SNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Covid Count Update
